### ISSUE TITLE
[Request] Add more Notification Provider

### ISSUE THREAD

**Issue by rolikeusch** [msgbyte/tianji#10]
would be great to have more notification provider like pushover, telegram, slack....

**Comment by moonrailgun** [comment]
telegram notification has been support in v1.3.0

**Comment by rolikeusch** [comment]
could [apprise](https://github.com/caronc/apprise) be a solution for more povider?

**Comment by moonrailgun** [comment]
of course, welcome to pr, or i can add it later

**Comment by svoop** [comment]
Guess this issue can be closed now as far as Apprise is concerned.

**Comment by moonrailgun** [comment]
yeah, closed
