### ISSUE TITLE
Agent memory leak

### ISSUE THREAD

**Issue by qhy040404** [msgbyte/tianji#103]
After running for a period of time, about a month, the agent's memory will leak from the initial 8MB to about 300MB, which is not friendly to some servers with limited memory.

**Comment by moonrailgun** [comment]
emmm, any screenshots?

**Comment by qhy040404** [comment]
![image](https://github.com/user-attachments/assets/5fe145a6-ead7-492f-8469-6e3b5bb08fda)
This problem can also be reproduced under Linux.

![image](https://github.com/user-attachments/assets/511189d1-deeb-4ff7-a02f-372c62a80c9d)
> After restart

**Comment by moonrailgun** [comment]
ok, thanks. i will check it.
thanks for your report.

**Comment by moonrailgun** [comment]
I think its has been fixed in recently version.

please try it, and let me know if its still has problem, thanks
