### ISSUE TITLE
Tracking code won't work with Ghost CMS?

### ISSUE THREAD

**Issue by zarevskaya** [msgbyte/tianji#123]
Hello, 

I am trying to get Tianji working with Ghost CMS. I have no return data for visits.

When I click on a page on my website, I see this, error 204:

![Screenshot_20241031_110707](https://github.com/user-attachments/assets/33a60e92-136e-4b5b-9192-1d94874f27ef)

Information is _received_, but nothing is displayed in Tianji.

Hany hint? Thanks in advance!

**Comment by moonrailgun** [comment]
can you provide more context?

for example a chrome devtool logs? or maybe you can provide your website then i can check it?

**Comment by zarevskaya** [comment]
Solved, it was a cors issue... 
Thanks for this cool app! I love it ;)

**Comment by moonrailgun** [comment]
well. how can this cors can resolve? i think i already added cors middleware

**Comment by zarevskaya** [comment]
I'm using [Cosmos Server](https://github.com/azukaar/Cosmos-Server).

There is an option to set CORS origin, like that:

![Screenshot_20241101_000238](https://github.com/user-attachments/assets/62daac93-4f15-4b85-9838-bc8512737e39)

Now, that work fine.

**Comment by moonrailgun** [comment]
okay, looks you are wrap tianji service with a gateway.

and this gateway disables cors by default for security reasons.

**Comment by zarevskaya** [comment]
That's correct. Thanks for the support.
