### ISSUE TITLE
 domain expiry date 

### ISSUE THREAD

**Issue by muhammeddemirdogen** [msgbyte/tianji#135]
hello, I can track domain ssl in tianji, but it doesn't seem to warn for the domain expiry date. I did a little research for this, it doesn't seem impossible. Can you add this feature to Tianji.

**Comment by moonrailgun** [comment]
i think i have been already added it. its not work?

![image](https://github.com/user-attachments/assets/d4aceaac-918a-4307-865a-04788a82d51b)


for example:

![image](https://github.com/user-attachments/assets/a63fbf95-d7a9-4f68-95b4-10e2512e0469)

**Comment by muhammeddemirdogen** [comment]
You're an excellent person. I thought it hadn't been added because the documents weren't there. Thank you.

**Comment by muhammeddemirdogen** [comment]
You're a wonderful person. I didn't see it in the documents, so I thought it hadn't been added. Thank you.

**Comment by moonrailgun** [comment]
you are welcome
