### ISSUE TITLE
[Bug] Stop/Start a Monitor will not work

### ISSUE THREAD

**Issue by rolikeusch** [msgbyte/tianji#15]
if you manually stop a monitor and start it again, it will no longer update.
<img width="807" alt="tianjo001" src="https://github.com/msgbyte/tianji/assets/3592156/ffeadfab-3fa9-4a31-98cd-e0050b6e4652">

and it looks like the alarming over telegram is not working. i never got a down message (mail works). 
(if i test the telegram bot, i get the test notification.)
I see this messages in the logs.

```
ok: false,
      error_code: 400,
      description: "Bad Request: can't parse entities: Character '.' is reserved and must be escaped with the preceding '\\'"
    }
```

or

```
data: {
      ok: false,
      error_code: 400,
      description: "Bad Request: can't parse entities: Character '-' is reserved and must be escaped with the preceding '\\'"
    }
```

...and there is a small typo when you stop  a monitor ;) should be stopped
<img width="212" alt="tianji002" src="https://github.com/msgbyte/tianji/assets/3592156/1d24ce90-e1bb-4ab6-a846-dbee7c99415d">

**Comment by moonrailgun** [comment]
okay, telegram has too many character problem, i will adapt it

and for manually stop/start, reload page can fix it?

**Comment by moonrailgun** [comment]
in my personal hosted tianji instance, start/ stop is work fine.

https://github.com/msgbyte/tianji/assets/6964737/5cfdba76-7c14-4ca6-ae7f-52de6fa9ea4f

if you manual start, monitor will run it once immediately

**Comment by rolikeusch** [comment]
i also checked it on your test instance, there is the same issue. if i start it again, it updates only once and then never again.

**Comment by moonrailgun** [comment]
oh, yes, you are right.

its a silly bug. but very serious. thanks for your report. ❤️

**Comment by moonrailgun** [comment]
v1.3.1 will be fix it quickly

**Comment by moonrailgun** [comment]
demo has been upgrade, work fine, closed

**Comment by rolikeusch** [comment]
> demo has been upgrade, work fine, closed

yes it works now.
