### ISSUE TITLE
微信群二维码过期，希望更新一下

### ISSUE THREAD

**Issue by gclm** [msgbyte/tianji#18]

**Comment by moonrailgun** [comment]
updated

**Comment by gclm** [comment]
![image](https://github.com/msgbyte/tianji/assets/27618687/938a0090-a565-4481-93d6-6820bfed879f)
没有更新

**Comment by moonrailgun** [comment]
sorry. network problem.
![image](https://github.com/msgbyte/tianji/assets/6964737/505426ce-d3c8-4eca-90a7-b4a2712c3584)


i direct put qrcode here.
![image](https://github.com/msgbyte/tianji/assets/6964737/e3984aee-eb60-49ea-947b-ded76735c2ba)
