### ISSUE TITLE
[Feature/Bug] Allow change script filename

### ISSUE THREAD

**Issue by gander** [msgbyte/tianji#37]
The `tracker.js` file may be on the blacklist of Ad-block solutions. If you could call it your own name, it would reduce the chances of detection. You could even do something like the JS Loader SDK in Sentry, the file name already conveys the tracking code identifier.

**Comment by moonrailgun** [comment]
cool. this is a good idea. i dont know its will block by adblock.
because i am using it

**Comment by gander** [comment]
I meant the name `tracker` itself. I would highly suspect that an ad-block plugin would block such a name by default. For example umami now calls this file simply `script` which would be very difficult to filter.
