### ISSUE TITLE
[FEATURE] Servers Graph + Previous period

### ISSUE THREAD

**Issue by gander** [msgbyte/tianji#41]
It would be great if server monitoring included information on all submitted statuses from the last day or even two days. This way, we could compare them because, while the current server state is nice and I really like it, it would be helpful to see how the load is distributed over time and compare it with the previous state. 

This is exactly what I was looking for in Open Source solutions, not to install a huge machine that gives me server status info, but I would need a bit more of that info. And if it's not too troublesome, it could be turned on with an optional flag. Maybe not everyone needs this and doesn't need the info, because it can be a lot and take up space in the database. So this optional feature, for those who really need it, activated by a flag, would be super awesome.

**Comment by moonrailgun** [comment]
yeah, i agree with you, but those data is too large, which maybe need a time series database. its will make install is more hard.

This is one of the reason why I haven't did this

**Comment by moonrailgun** [comment]
but i hear you

**Comment by gander** [comment]
And sending this data further to the queue, as in the case of this application?

https://shlink.io/documentation/advanced/real-time-updates/

**Comment by moonrailgun** [comment]
This is not suitable for scenarios with large data. 

We plan support short-term data trend viewing in the future, with client side

As for long-term data persistence, I need to think about it
