### ISSUE TITLE
[FEATURE] User Consent for Monitoring Proposal

### ISSUE THREAD

**Issue by gander** [msgbyte/tianji#42]
I think you could add something for yourself in this solution, like asking users if they agree to monitoring from the Sentry. For example, to collect information about how their apps work and if there are errors, which will also help in development. At the same time, this feature could be an option for users who don't want to give you this data but would like to use the information themselves and could use it to connect their own Sentry.

**Comment by moonrailgun** [comment]
Can you explain your thoughts in more detail, because I don’t understand how it is related to sentry?

**Comment by gander** [comment]
Let your imagination run wild, but my point is that you might want to collect information about how your app is performing for other users, performance and bugs, and connect Sentry or another tool to that

**Comment by moonrailgun** [comment]
ok i get your mind, but its very deep feature.

It would be better to leave it to other services that specialize in bug tracking.

Or you can use some simple sdk to report the event: but there are no details
