### ISSUE TITLE
[Question] Support MySQL

### ISSUE THREAD

**Issue by ToshY** [msgbyte/tianji#47]
Hello 👋 

Doe tianji support databases like MySQL besides Postgres? I can not seem to find any mention of it currently supporting other database types in the docs or docker compose example. 

Thanks in advance.

**Comment by moonrailgun** [comment]
yes, not add mysql support yet because tianji has use some advanced pg feature which mysql not include.

**Comment by ToshY** [comment]
Okay thanks for letting me know 🙂
