### ISSUE TITLE
[BUG][PAGE] Custom domain is required?

### ISSUE THREAD

**Issue by gander** [msgbyte/tianji#57]
Custom domain is required? Or need more details.

![obraz](https://github.com/msgbyte/tianji/assets/421597/b40e3096-7286-49b5-9dfa-bc6639604002)

**Comment by moonrailgun** [comment]
let me check

**Comment by moonrailgun** [comment]
its a stupid bug and i am release a hotfix v1.9.2 which fixed this issue

thanks for your report
