### ISSUE TITLE
Typography bug

### ISSUE THREAD

**Issue by andriilive** [msgbyte/tianji#61]
**Typo bug**

![CleanShot 2024-05-05 at 03 46 06](https://github.com/msgbyte/tianji/assets/43708848/f471eca3-94a3-4f28-a2ec-9193263eb797)

**Comment by moonrailgun** [comment]
emmmm. where?

**Comment by andriilive** [comment]
The font-family in 3Dots menu dropdown at boron is serif. 

![image](https://github.com/msgbyte/tianji/assets/43708848/a20401d5-87e7-4107-adcd-381da884d9da)

**Comment by moonrailgun** [comment]
Oh nice catch, i will fix it before this release

**Comment by ruohki** [comment]
still a thing
