### ISSUE TITLE
[Bug] Dashboard interface name will not be synchronized with Monitor

### ISSUE THREAD

**Issue by B3nDan** [msgbyte/tianji#7]
![Shot 2024-01-03 at 14 19 43@2x](https://github.com/msgbyte/tianji/assets/129975925/a2be26b7-b89e-44e7-9679-e42b7c863d6e)
![Shot 2024-01-03 at 14 23 51@2x](https://github.com/msgbyte/tianji/assets/129975925/5f1639ac-0d3f-41f4-8696-22b035bec316)

最开始我设置一个名为 `Store` 的 Monitor ，并且固定在了 Dashboard
接着，我修改了这个 Monitor 的名字，发现无论怎么刷新，Dashboard 的名称都不会改

**Comment by moonrailgun** [comment]
yeah, we will support change it in layout editor later.

There is no direct relationship between the two part

**Comment by moonrailgun** [comment]
v1.3.0 has been support

**Comment by moonrailgun** [comment]
one a card title, the another is website name

some card not have their own title. website is an exception
