### ISSUE TITLE
[report] the latest docker image should be moonrailgun/tianji:1.11.3

### ISSUE THREAD

**Issue by shynome** [msgbyte/tianji#77]
goto `http://127.0.0.1:12345/settings/notifications` , only show `Hello /settings!`

**Comment by shynome** [comment]
the version 1.11.3 is fixed, but docker image 1.11.3 is not found

**Comment by SalimQS** [comment]
Latest tianji version in Docker Hub is v1.11.2, i tried installed it without docker, and it work to me.
Ref: https://tianji.msgbyte.com/docs/install/manual

**Comment by shynome** [comment]
[v1.11.1](https://github.com/msgbyte/tianji/releases/tag/v1.11.1) should be work, it is changed at [v1.11.2](https://github.com/msgbyte/tianji/releases/tag/v1.11.2) ([328a4e8](https://github.com/msgbyte/tianji/commit/328a4e856cee0cf38c0beb1611ac2bc643bbd981#diff-f88b276cf9da43287230587854be51f5faaa57fcf775ebfce3fe457543f22342)), and fixed at [v1.11.3](https://github.com/msgbyte/tianji/releases/tag/1.11.3) ([fdce6b4](https://github.com/msgbyte/tianji/commit/fdce6b42f1e9817dba76072adaf732040bf3f8d3))

this problem is seem tianji team forget publish v1.11.3 tag

**Comment by moonrailgun** [comment]
my bad, tag marked as `1.11.3` rather than `v1.11.3`

**Comment by moonrailgun** [comment]
too busy, see it just now

**Comment by shynome** [comment]
Oh yeah,the lastest docker image now is 1.11.3
