### ISSUE TITLE
Notification via SMTP doesn't work

### ISSUE THREAD

**Issue by infocillasas** [msgbyte/tianji#78]
Hi,

When I try to setup an email notification (SMTP) in the settings menu, nothing happens when I press the buttons "Test" or "Save". There is nothing in the logs. No email is sent. 

Did I missed something ?

Setup: docker on a bare metal Debian machine. I use Apache reverse proxy and the "ports" section of my docker-compose.yml file is setup with "127.0.0.1:12345:12345"

Thanks

**Comment by moonrailgun** [comment]
I think SMTP logic is correct. is any error report from server side?

**Comment by infocillasas** [comment]
Sorry, I didn't see that there is a page bottom to setup the receiver's email...
Everything works fine.

Thank you
