### ISSUE TITLE
[Bug] Feed feature on light theme has black bg with black text, no readable

### ISSUE THREAD

**Issue by GabrielRozendo** [msgbyte/tianji#80]
v1.12.0 on Light theme

Feed feature, after created a channel, the board is black background with black text, no readable.
I can select the text and read on highlight and it is ok.

No problem on dark mode tho.
  
![CleanShot 2024-07-23 at 09 46 37](https://github.com/user-attachments/assets/a3acd193-d583-408f-95d4-ba15f9158e85)

sent the first request to try and then no problem anymore:
![CleanShot 2024-07-23 at 09 51 59](https://github.com/user-attachments/assets/b9bd057b-f57e-403a-acf6-5f7de5bdd44a)

same problem on integration (both GitHub and custom)
![CleanShot 2024-07-23 at 09 56 21](https://github.com/user-attachments/assets/fbfffe03-0b80-4458-99b1-cb38b6732955)

ps.: it could be a `curl` command in example instead a js (or both).

**Comment by GabrielRozendo** [comment]
same problem on integration
![CleanShot 2024-07-23 at 09 56 21](https://github.com/user-attachments/assets/fbfffe03-0b80-4458-99b1-cb38b6732955)

**Comment by moonrailgun** [comment]
Sorry, i will fix it quickly

and thanks for your report

**Comment by moonrailgun** [comment]
fixed in v1.12.1
