### ISSUE TITLE
Status Page Sort

### ISSUE THREAD

**Issue by zhuweiji** [msgbyte/tianji#98]
Hey there @moonrailgun! Great work with this repo, the aesthetics choices are well done and the API is lightning quick too.

I have a suggestion for the status page:

![image](https://github.com/user-attachments/assets/5c2cd3c9-0094-438b-8d4b-90967cc035e1)

Currently, I might want to see different views over the page, such as:

1. Currently Down pages first
2. Highest latency first
etc. 

I'm thinking this could be a selector on the page. This will help a user to to view at a glance if their system is healthy.

![image](https://github.com/user-attachments/assets/19e2e38d-73da-4c4a-881c-755b5a11a8aa)

If you think this is a good idea, I can work with you to get this implemented. Thanks!

**Comment by moonrailgun** [comment]
i think its a good idea!
did you wanna submit a PR about it?

i am current refactor status page which can support more complex feature and display way. maybe you can waiting next version if you wanna create a feature about it.

**Comment by zhuweiji** [comment]
sure, I'll wait then. If you can fit this feature inside your refactor,
that would be much appreciated too 👍

**Comment by zhuweiji** [comment]
I took a stab at this yesterday, the state for each monitor is all the way down in each MonitorListItem while we would probably want to put the sort component in ServiceStatusPage or MonitorListPage. Not sure how to tackle this.

Also, I think more comprehensive documentation for contributors on the README would help future developers - currently, the only docs are on the website, about db migration. I could also take a quick stab at that sometime later if you want.

**Comment by moonrailgun** [comment]
i finish monitor status page refactor recently, now we can publish ordered monitor list, and group monitors.

feel free to check it in v1.15.x

**Comment by zhuweiji** [comment]
Is there documentation about creating an ordered monitor list?

**Comment by moonrailgun** [comment]
> Is there documentation about creating an ordered monitor list?

just simple drag it.
